---

config_dnsmasq: true  #defines if DNSMASQ should be configured
dhcp_boot: 'pxelinux.0,{{ inventory_hostname }},{{ pri_bind_address }}'
dhcp_scopes:  #define dhcp scopes to be used if dhcp is enabled
  - start: 192.168.1.128
    end: 192.168.1.224
    netmask: 255.255.255.0
  - start: 192.168.2.128
    end: 192.168.2.224
    netmask: 255.255.255.0
dns_search: '{{ domain_name }}' #define your dns search here or define globally in group_vars/all
dnsmasq_add_custom_domain: true  #defines if dnsmasq should be configured for internal
dnsmasq_enable_forwarders: true  #defines if forwarders should be used
dnsmasq_nameservers:  #define your dns servers here or define globally in group_vars/all
  - 8.8.4.4
  - 8.8.8.8
enable_dnsmasq_dhcp: false  #defines if DHCP services are provided by DNSMASQ
enable_dnsmasq_dhcp_tftp: false  #defines if DHCP and TFTP services are provided by DNSMASQ
enable_tftp: false  #defines if TFTP services are provided by DNSMASQ
ntp_servers:  #defines ntp servers for clients to poll
  - 131.107.13.100
  - 216.228.192.69
pri_bind_address: '{{ ansible_default_ipv4.address }}'
pri_bind_interface: '{{ ansible_default_ipv4.interface }}'
pri_domain_name: '{{ domain_name }} '
pri_netmask_cidr: 24  #defines netmask cidr value 255.255.255.0 == 24
pri_network: '{{ ansible_default_ipv4.network }}'
tftpboot_dir: /var/lib/tftpboot  #Define tftpboot directory
