---

- name: "config_apache2 | Ensuring Apache2 Website(s) DocumentRoot Folders Exist"
  file:
    path: "{{ item.documentroot }}"
    state: "directory"
    owner: "{{ apache2_web_owner }}"
    group: "{{ apache2_web_group }}"
  with_items: '{{ apache2_virtual_hosts }}'

- name: "config_apache2 | Ensuring Apache2 Logs Folder Exists"
  file:
    path: "{{ apache2_log_dir }}"
    state: "directory"

- name: "config_apache2 | Configuring Apache2 Website(s)"
  template:
    src: "etc/apache2/sites-available/000-default.conf.j2"
    dest: "/etc/apache2/sites-available/000-default.conf"
  notify:
    - "restart apache2"
