---

- name: "Updating /etc/hosts (localhost)"
  template:
    src: "etc/hosts.j2"
    dest: "/etc/hosts"
    owner: root
    group: root
    mode: 0644

- name: "Updating /etc/hosts (All hosts in play)"
  lineinfile:
    dest: /etc/hosts
    regexp: ".*{{ item }}$"
    line: "{{ hostvars[item].ansible_default_ipv4.address }} {{ item }}"
    state: present
  with_items: groups['all']
  when: >
        (etc_hosts_add_all_hosts is defined and etc_hosts_add_all_hosts) and
        hostvars[item].ansible_default_ipv4.address is defined
